<?php

namespace Freifunk\StatisticBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * @param Link $link
     * @return Link
     */
    public function findExistingLink(Link $link)
    {
        $qb = $this->createQueryBuilder('l');
        $qb->andWhere($qb->expr()->eq('l.source', $qb->expr()->literal($link->getSource()->getId())));
        $qb->andWhere($qb->expr()->eq('l.target', $qb->expr()->literal($link->getTarget()->getId())));
        $qb->andWhere($qb->expr()->eq('l.type', $qb->expr()->literal($link->getType())));
        $qb->andWhere($qb->expr()->isNull('l.closedAt'));
        return $qb->getQuery()->getOneOrNullResult();
    }
}
