<?php

namespace Freifunk\StatisticBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{

    /**
     * @param $mac
     * @return Node
     */
    public function findByMac($mac)
    {
        $qb = $this->createQueryBuilder("n");
        $qb->andWhere($qb->expr()->eq("n.mac", $qb->expr()->literal($mac)));
        return $qb->getQuery()->getOneOrNullResult();
    }
}
